-- =====================================================================
-- Esquema inicial - Zoológico + Acuario (modelo simplificado, 11 tablas)
-- Motor: PostgreSQL 10+
-- Las PK son IDENTITY "BY DEFAULT": podés insertar ids explícitos (el
-- seed lo hace) o dejar que se generen solos.
-- =====================================================================

-- ---------------------------------------------------------------------
-- Infraestructura
-- ---------------------------------------------------------------------
CREATE TABLE recinto (
  id_recinto  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre      TEXT    NOT NULL UNIQUE,
  tipo        TEXT    NOT NULL CHECK (tipo IN ('terrestre', 'acuático')),
  capacidad   INTEGER NOT NULL CHECK (capacidad > 0)
);

-- 1:1 con recinto: la PK es a la vez FK, así cada recinto tiene como
-- máximo un tanque. (Convención: solo los recintos de tipo 'acuático'.)
CREATE TABLE tanque (
  id_recinto      INTEGER PRIMARY KEY
                  REFERENCES recinto (id_recinto) ON DELETE CASCADE,
  volumen_litros  INTEGER       NOT NULL CHECK (volumen_litros > 0),
  temp_objetivo   NUMERIC(4,1)  NOT NULL
);

-- ---------------------------------------------------------------------
-- Animales
-- ---------------------------------------------------------------------
CREATE TABLE especie (
  id_especie           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_comun         TEXT NOT NULL UNIQUE,
  estado_conservacion  TEXT
);

-- 1:N: un recinto y una especie tienen muchos animales
CREATE TABLE animal (
  id_animal         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre            TEXT    NOT NULL,
  fecha_nacimiento  DATE,
  id_especie        INTEGER NOT NULL REFERENCES especie (id_especie),
  id_recinto        INTEGER NOT NULL REFERENCES recinto (id_recinto)
);

-- ---------------------------------------------------------------------
-- Personal
-- ---------------------------------------------------------------------
CREATE TABLE empleado (
  id_empleado  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre       TEXT NOT NULL,
  cargo        TEXT NOT NULL
);

-- N:M empleado - recinto
CREATE TABLE asignacion (
  id_empleado  INTEGER NOT NULL REFERENCES empleado (id_empleado) ON DELETE CASCADE,
  id_recinto   INTEGER NOT NULL REFERENCES recinto (id_recinto)   ON DELETE CASCADE,
  turno        TEXT    NOT NULL CHECK (turno IN ('mañana', 'tarde', 'noche')),
  PRIMARY KEY (id_empleado, id_recinto)
);

-- 1:N con animal y con empleado (el que atiende; en la práctica, un
-- empleado con cargo 'veterinario')
CREATE TABLE consulta (
  id_consulta  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_animal    INTEGER NOT NULL REFERENCES animal (id_animal),
  id_empleado  INTEGER NOT NULL REFERENCES empleado (id_empleado),
  fecha        DATE    NOT NULL DEFAULT CURRENT_DATE,
  diagnostico  TEXT
);

-- ---------------------------------------------------------------------
-- Visitantes y actividades
-- ---------------------------------------------------------------------
CREATE TABLE visitante (
  id_visitante  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre        TEXT NOT NULL,
  email         TEXT UNIQUE
);

CREATE TABLE entrada (
  id_entrada    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_visitante  INTEGER       NOT NULL REFERENCES visitante (id_visitante),
  fecha_visita  DATE          NOT NULL,
  precio        NUMERIC(10,2) NOT NULL CHECK (precio >= 0)
);

CREATE TABLE actividad (
  id_actividad  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre        TEXT    NOT NULL,
  horario       TIME    NOT NULL,
  cupo          INTEGER NOT NULL CHECK (cupo > 0),
  id_recinto    INTEGER NOT NULL REFERENCES recinto (id_recinto)
);

-- N:M entrada - actividad
CREATE TABLE reserva (
  id_entrada         INTEGER NOT NULL REFERENCES entrada (id_entrada) ON DELETE CASCADE,
  id_actividad       INTEGER NOT NULL REFERENCES actividad (id_actividad),
  cantidad_personas  INTEGER NOT NULL DEFAULT 1 CHECK (cantidad_personas > 0),
  PRIMARY KEY (id_entrada, id_actividad)
);

-- ---------------------------------------------------------------------
-- Índices sobre las FK (Postgres no los crea solo)
-- ---------------------------------------------------------------------
CREATE INDEX idx_animal_especie    ON animal     (id_especie);
CREATE INDEX idx_animal_recinto    ON animal     (id_recinto);
CREATE INDEX idx_asignacion_recinto ON asignacion (id_recinto);
CREATE INDEX idx_consulta_animal   ON consulta   (id_animal);
CREATE INDEX idx_consulta_empleado ON consulta   (id_empleado);
CREATE INDEX idx_entrada_visitante ON entrada    (id_visitante);
CREATE INDEX idx_actividad_recinto ON actividad  (id_recinto);
CREATE INDEX idx_reserva_actividad ON reserva    (id_actividad);

