apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: api
  namespace: app
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: api
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 10s
