name: bdd-sys

services:
  postgres-ui:
    image: ghcr.io/drizzle-team/gateway:latest
    container_name: axum-drizzle
    restart: unless-stopped
    ports:
      - "4983:4983"
    environment:
      MASTERPASS: ${MASTERPASS:-change-me}
      DATABASE_URL_app: "postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${POSTGRES_DB:-app}"
    volumes:
      - drizzle-data:/app
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:alpine3.24
    container_name: axum-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-app}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10

  redis:
    image: redis:alpine3.23
    container_name: axum-redis
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  pgdata:
  redisdata:
  drizzle-data:
