apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: postgres
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgres
    spec:
      nodeSelector:
        data: pg # el worker que tiene montado /data/pg (ver kind.config.yaml)
      containers:
        - name: postgres
          image: postgres:alpine3.24
          ports:
            - name: pg
              containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres # TODO: CHANGE ME!!!
            - name: POSTGRES_DB
              value: app
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql # without /data because of the new versions.
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres", "-d", "app"] # hardcoded for now, but can be changed to env variables if needed.
            periodSeconds: 5
      volumes:
        - name: data
          hostPath:
            path: /data/pg
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app.kubernetes.io/name: postgres
  ports:
    - name: pg
      port: 5432
      targetPort: pg
